<?php
declare(strict_types=1);

// This file was autogenerated by uniffi-bindgen-php.

namespace {{ namespace }};

{% import "macros.php" as php %}
{% include "Types.php" %}

{{ type_definitions }}

{% for func in functions %}
{% include "TopLevelFunctionTemplate.php" %}
{% endfor %}

{% for obj in objects %}
{% include "ObjectTemplate.php" %}
{% endfor %}
